routes/web.php
<?php
// Route::get('roles', function(){
//     return \App\Role::with('user')->get();
// });

Route::get('/', function () { return view('welcome'); });
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/privacity', 'HomeController@privacity');
Route::get('/terms', 'HomeController@terminos');
Route::get('activate/{token}', 'ActivationTokenController@activate')->name('activation');

Auth::routes();

Route::resource('lista_partidos_oficiales', 'MatchController');
Route::resource('usuarios', 'UsersController');

Route::get('config14605145pro', 'QuinielaController@configApp')->name('configApp');
Route::get('config1968pro', 'QuinielaController@configQuinielas')->name('configQuinielas');
Route::get('cerrarpartido/{grupo}/{code}/{active}', 'QuinielaController@CerrarPartido');

Route::get('isadmintrue', 'ListaUsuariosController@isadminRole');

Route::get('ActualizarPuntosPartido/{code}', 'PointController@ActualizarPuntosPartido');

Route::get('tabla2', 'PointController@tabla2');

Route::get('configtablaPosiciones/{desde?}/{hasta?}', 'PositionController@basePosition');
Route::get('ActualizarPuntosPartido/{code}', 'PointController@procesarPartidoyCargarPuntos');
Route::get('tabla', 'PositionController@index');




Route::resource('quiniela', 'QuinielaController');
Route::resource('grupoA', 'GrupoAController');
Route::resource('grupoB', 'GrupoBController');
Route::resource('grupoC', 'GrupoCController');
Route::resource('grupoD', 'GrupoDController');
Route::resource('grupoE', 'GrupoEController');
Route::resource('grupoF', 'GrupoFController');
Route::resource('grupoG', 'GrupoGController');
Route::resource('grupoH', 'GrupoHController');

Route::get('resumen/{usuario?}', 'QuinielaController@index');


Route::get('lista', 'ListaUsuariosController@index');
Route::get('favoritas', 'ListaUsuariosController@favoritas');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Auth;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'apellido', 'birthday', 'cedula', 'img', 'telefono', 'email', 'password', 'active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
    
    public function activate()
    {
        $this->update(['active' => true]);
        Auth::login($this);
        $this->token->delete();
    }

    public function token()
    {
        return $this->hasOne(ActivationToken::class);
    }

    public function generateToken()
    {
        $this->token()->create([           
            'token'  => str_random(60)
        ]);
        return $this;
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class, 'assigned_roles');
    }

    public function hasRoles(array $roles)
    {
        foreach($roles as $role)
        {
            foreach($this->roles as $userRole)
            {
                if($userRole->name === $role)
                {
                    return true;
                }
            }              
        }
        return false;
    }

    public function isAdmin()
    {
        return $this->hasRoles(['admin']);
    }
    public function point()
    {
        return $this->belongsTo(Point::class);
    }

    public function favoritas()
    {
        return $this->belongsToMany(Favorito::class);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Policies\UserPolicy;
use App\Http\Requests\updateUserRequest;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
        $this->middleware('roles:admin', ['except'=> ['edit', 'update', 'show']]);

    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);        
        return view( 'users.show', compact('user') );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $this->authorize($user);
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateUserRequest $request, $id)
    {
        $user = User::findOrFail($id);
        $this->authorize($user);
        $user->update($request->all());
        return back()->with('info', 'Usuario Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);   
        $this->authorize($user);     
        $user->update(['active' => false]);
        return redirect('/')->with('info', 'Usuario eliminado');
    }

    public function subir_imagen_usuario(Request $request)
	{
	    $id = $request->input('img');
		$archivo = $request->file('archivo');
        $input  = array('image' => $archivo) ;
        $reglas = array('image' => 'required|image|mimes:jpeg,jpg,bmp,png,gif|max:900');

        $validacion = Validator::make($input,  $reglas);

        if ($validacion->fails())
        {
          return view("mensajes.msj_rechazado")->with("msj","El archivo no es una imagen valida");
        }
        else
        {
	        $nombre_original = $archivo->getClientOriginalName();
			$extension = $archivo->getClientOriginalExtension();
            $nuevo_nombre = "userimagen-".$id.".".$extension;
            
		    $r1 = Storage::disk('fotografias')->put($nuevo_nombre,  \File::get($archivo) );
		    $rutadelaimagen = "fotografias/".$nuevo_nombre;
	    
		    if ($r1){
			    $usuario = User::find($id);
			    $usuario->imagenurl = $rutadelaimagen;
			    $r2 = $usuario->save();
		        return view("mensajes.msj_correcto")->with("msj","Imagen agregada correctamente");
            }
        }
    }

    public function cambiar_password(Request $request)
    {
        $id = $request->input("id_usuario_password");
        $email = $request->input("email_usuario");
        $password = $request->input("password_usuario");
        $usuario = User::find($id);
        $usuario->email = $email;
        $usuario->password = bcrypt($password);
        $r = $usuario->save();

        if ($r) {
            return view("mensajes.msj_correcto")->with("msj", "password actualizado");
        } else {
            return view("mensajes.msj_rechazado")->with("msj", "Error al actualizar el password");
        }
    }
}

resources/views/users/create.blade.php
Hola desde create users

resources/views/users/edit.blade.php
@extends('layouts.master')
@section('content')
   
   
   @if(session()->has('info'))
    <div class="alert alert-success">{{ session('info') }}</div>
    @endif
    

    <div class="row">
        <div class="col-sm-6">
            <div class="box box-info">
                <div class="box-header with-border">
                        <h2>Editar usuario</h2>
                        <form method="POST" action="{{ route('usuarios.update', $user->id) }}">
                                {!! method_field('PUT') !!}
                                {!! csrf_field() !!}
                                    <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                                        <label for="nombre" class="col-md-4 control-label">Nombre</label>
                
                                            <div class="col-md-6">
                                                <input id="name" type="text" class="form-control" name="nombre" value="{{ $user->nombre }}" required autofocus>
                
                                                @if ($errors->has('nombre'))
                                                    <span class="help-block">
                                                        <strong>{{ $errors->first('nombre') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                    </div>
                
                                    <div class="form-group{{ $errors->has('apellido') ? ' has-error' : '' }}">
                                        <label for="apellido" class="col-md-4 control-label">Apellido</label>
                
                                        <div class="col-md-6">
                                            <input id="name" type="text" class="form-control" name="apellido" value="{{ $user->apellido }}" required autofocus>
                
                                            @if ($errors->has('apellido'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('apellido') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                
                                    <div class="form-group{{ $errors->has('birthday') ? ' has-error' : '' }}">
                                        <label for="birthday" class="col-md-4 control-label">Fecha de Nacimiento</label>    
                                        <div class="col-md-6">
                                            <input id="birthday" type="date" class="form-control" name="birthday" value="{{ $user->birthday }}" required autofocus>
                
                                            @if ($errors->has('birthday'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('birthday') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                
                                    <div class="form-group{{ $errors->has('cedula') ? ' has-error' : '' }}">
                                        <label for="cedula" class="col-md-4 control-label">Cédula de identidad</label>
                
                                        <div class="col-md-6">
                                            <input id="name" type="number" class="form-control" name="cedula" value="{{ $user->cedula }}" required autofocus>
                
                                            @if ($errors->has('cedula'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('cedula') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                
                                    <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                                        <label for="telefono" class="col-md-4 control-label">telefono</label>
                
                                        <div class="col-md-6">
                                            <input id="name" type="text" class="form-control" name="telefono" value="{{ $user->telefono }}" required autofocus>
                
                                            @if ($errors->has('telefono'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('telefono') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                
                                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                        <label for="email" class="col-md-4 control-label">E-Mail</label>
                
                                        <div class="col-md-6">
                                            <input id="email" type="email" class="form-control" name="email" value="{{ $user->email }}" required>
                
                                            @if ($errors->has('email'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('email') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                <hr>    
                                    <br>
                
                                    <div class="form-group">
                                        <div class="col-md-6 col-md-offset-4">
                                            <button type="submit" class="btn btn-primary btn-block">
                                                Actualizar
                                            </button>
                                        </div>
                                    </div>
                                </form> 
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive img-circle" src="{{ auth()->user()->img }}" alt="User profile picture">
            
                    <h3 class="profile-username text-center">{{ auth()->user()->nombre }} {{ auth()->user()->apellido }}</h3>
    
                    <p class="text-muted text-center">Player {{ auth()->user()->id }}</p>
    
                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <b>Cambiar imagen</b> <a class="pull-right">1,322</a>
                        </li>                    
                    </ul>
                    </div>                       
                </div>
        </div>
    </div>

    
        
@endsection

resources/views/users/index.blade.php
@extends('layouts.master')
@section('content')
   
   <h1>Lista de Usuarios</h1>
    @if( session()->has('info') )
        <div class="alert alert-success">{{ session('info') }}</div> 
    @endif
    
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Role</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td> <a href=" usuarios/{{ $user->id  }}" >{{ $user->nombre }}</a></td>
                <td>{{ $user->email }}</td>
                <td>
                    @foreach($user->roles as $role)
                        {{ $role->display_name }}
                   @endforeach
                </td>
                <td> 
                    <a href=" {{ route('usuarios.edit', $user->id) }}" class="btn btn-info btn-xs">Editar</a> 
                    <form style="display:inline" method="POST" action="{{ route('usuarios.destroy',  $user->id) }}">
                        <button type="submit" class="btn btn-danger btn-xs">Eliminar</button>
                        {!! csrf_field() !!}
                        {!! method_field('DELETE') !!}
                    </form>
                </td>
               
            </tr>
           
            @endforeach
        </tbody>
    </table>

  


    
@endsection

resources/views/users/show.blade.php
@extends('layouts.master')
@section('content')
<div class="row">   
    <div class="col-sm-12">
        <div class="box box-info">
            <div class="box-header with-border">
                <h1>{{ $user->name }}</h1>
                <table class="table table-bordered table-striped">       
                        <tr>               
                            <th>Nombre y apellido</th>
                            <td>{{ $user->nombre }} {{ $user->apellido }} </td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ $user->email }}</td>
                        </tr> 
                        <tr>
                            <th>Roles</th>
                            <td>
                                @foreach($user->roles as $role)
                                {{ $role->display_name }}
                                @endforeach
                            </td>
                        </tr>               
                </table>                
            </div>
        </div>
    </div>
</div>
    

    @can('edit', $user)
    <a href="{{ route('usuarios.edit', $user->id) }}" class="btn btn-info">Editar</a>
    @endcan

 
@stop