routes/web.php
<?php
// Route::get('roles', function(){
//     return \App\Role::with('user')->get();
// });

Route::get('/', function () { return view('welcome'); });
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/privacity', 'HomeController@privacity');
Route::get('/terms', 'HomeController@terminos');
Route::get('activate/{token}', 'ActivationTokenController@activate')->name('activation');

Auth::routes();

Route::resource('lista_partidos_oficiales', 'MatchController');
Route::resource('usuarios', 'UsersController');

Route::get('config14605145pro', 'QuinielaController@configApp')->name('configApp');
Route::get('config1968pro', 'QuinielaController@configQuinielas')->name('configQuinielas');
Route::get('cerrarpartido/{grupo}/{code}/{active}', 'QuinielaController@CerrarPartido');

Route::get('isadmintrue', 'ListaUsuariosController@isadminRole');

Route::get('ActualizarPuntosPartido/{code}', 'PointController@ActualizarPuntosPartido');

Route::get('tabla2', 'PointController@tabla2');

Route::get('configtablaPosiciones/{desde?}/{hasta?}', 'PositionController@basePosition');
Route::get('ActualizarPuntosPartido/{code}', 'PointController@procesarPartidoyCargarPuntos');
Route::get('tabla', 'PositionController@index');




Route::resource('quiniela', 'QuinielaController');
Route::resource('grupoA', 'GrupoAController');
Route::resource('grupoB', 'GrupoBController');
Route::resource('grupoC', 'GrupoCController');
Route::resource('grupoD', 'GrupoDController');
Route::resource('grupoE', 'GrupoEController');
Route::resource('grupoF', 'GrupoFController');
Route::resource('grupoG', 'GrupoGController');
Route::resource('grupoH', 'GrupoHController');

Route::get('resumen/{usuario?}', 'QuinielaController@index');


Route::get('lista', 'ListaUsuariosController@index');
Route::get('favoritas', 'ListaUsuariosController@favoritas');

resources/views/layouts/partials/cargando.blade.php
<div style="display: none;" id="cargando" align="center">
    <br>
    <label style="color:#FFF; background-color:#ABB6BA; text-align:center">&nbsp;&nbsp;&nbsp;Espere... &nbsp;&nbsp;&nbsp;</label>
    <img src="/img/cargando.gif" align="middle" alt="cargador"> &nbsp;
    <label style="color:#ABB6BA">Realizando tarea solicitada ...</label>
    <br>
    <hr style="color:#003" width="50%">
    <br>
</div>

resources/views/layouts/partials/footer.blade.php
 <footer class="main-footer">

    <div class="pull-right hidden-xs">
      Diario La Nación
    </div>
    <a href="privacity">Privacy Policy</a> - 
    <a href="terms">Terms</a>
    <strong>Copyright &copy; 2016 <a href="#">DLN - GolPro</a>.</strong> All rights reserved.
  </footer>

  <script src="{{asset('js/web.js')}}"></script>
  <script src="https://golpro.test/js/app.js"></script>

resources/views/layouts/partials/head.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>GolPRo | Diario La Nación</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('css/web.css')}}">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120786343-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-120786343-1');
  </script>
</head>

resources/views/layouts/partials/leftbar.blade.php
    <aside class="main-sidebar">
        <section class="sidebar">
      
            <div class="user-panel">
               @auth
                <div class="pull-left image">
                <img src="{{ auth()->user()->img }}" class="img-circle" alt="User Image">
                </div>
               
                <div class="pull-left info">
               
                <p>{{ auth()->user()->nombre }}</p>         
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
                 @endauth
            </div>
    
            
            @include('layouts.partials.menuleft')
                 
        </section>
    </aside>
    

resources/views/layouts/partials/logo.blade.php
<a href="/home" class="logo">
    {{--  <!-- mini logo for sidebar mini 50x50 pixels -->  --}}
    <span class="logo-mini"><b>G</b>P</span>
    {{--  <!-- logo for regular state and mobile devices -->  --}}
    <span class="logo-lg"><b>GOL</b>PRO</span>
</a>

resources/views/layouts/partials/menuleft.blade.php
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header" >Menú Admin</li> 
@if( auth()->user()->hasRoles(['admin']) )
        
    <li class="treeview">
        <a href="#"><i class="fa fa-dashboard"></i> <span>usuarios</span>
            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
        </a>            
        <ul class="treeview-menu">
            <li><a href="{{route('usuarios.index')}}"><i class="fa fa-link"></i>Lista</a></li>
        </ul>
    </li>

    <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>Partidos Ofic.</span>
            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
        </a>            
        <ul class="treeview-menu">
            <li><a href="{{route('lista_partidos_oficiales.index')}}"><i class="fa fa-link"></i> <span>Lista</span></a></li>
            <li><a href="{{route('lista_partidos_oficiales.create')}}"><i class="fa fa-link"></i> <span>Agregar </span></a></li>
            <li><a href="#"><i class="fa fa-link"></i> <span>Eliminar</span></a></li>
        </ul>
    </li>    
        
@endif


    <li class=""><a href="/home" ><i class="fa fa-table"></i>Reglas de la Quiniela  </a> </li>

    <li class="treeview active menu-open">
        
        <a href="#"><i class="fa fa-dashboard"></i> <span>Fase de grupos</span>
            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
        </a>            
        <ul class="treeview-menu">       
            <li class=""><a href="/grupoA" ><i class="fa fa-table"></i> Grupo A  </a> </li>
            <li class=""><a href="/grupoB" ><i class="fa fa-table"></i> Grupo B  </a> </li>
            <li class=""><a href="/grupoC" ><i class="fa fa-table"></i> Grupo C  </a> </li>
            <li class=""><a href="/grupoD" ><i class="fa fa-table"></i> Grupo D  </a> </li>
            <li class=""><a href="/grupoE" ><i class="fa fa-table"></i> Grupo E  </a> </li>
            <li class=""><a href="/grupoF" ><i class="fa fa-table"></i> Grupo F  </a> </li>
            <li class=""><a href="/grupoG" ><i class="fa fa-table"></i> Grupo G  </a> </li>
            <li class=""><a href="/grupoH" ><i class="fa fa-table"></i> Grupo H  </a> </li>
            <li class=""><a href="/resumen" ><i class="fa fa-table"></i><b>Resumen </b>  </a> </li>            
        </ul>
    </li>
 
    <li class="treeview active menu-open">
        <a href="#"><i class="fa fa-soccer-ball-o"></i> <span>Ver Quinielas.</span>
            <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
        </a>            
        <ul class="treeview-menu"> 
            <li>
                <a href="/lista"><i class="fa fa-file-text-o"></i> <span>Participantes</span></a>              
            </li> 
            <li>
                <a href="/tabla"><i class="fa fa-file-text-o"></i> <span>Tabla de Posiciones</span></a>              
            </li> 
            
            {{--  <li>
                <a href="/favoritas"><i class="fa fa-file-text-o"></i> <span>Quinielas favoritas</span></a>              
            </li>    --}}
        </ul>
    </li>
         

</ul>

    

resources/views/layouts/partials/messages.blade.php
            <li class="dropdown messages-menu">            
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-envelope-o"></i>
                <span class="label label-success">4</span>
                </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>                
                <ul class="menu">
                  <li>
                    <a href="#">
                      <div class="pull-left">                      
                        <img src="img/player.jpg" class="img-circle" alt="User Image">
                      </div>                     
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>                      
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>                  
                </ul>               
                </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>  

resources/views/layouts/partials/modalesYbotones.blade.php
<section> 
        <div id="capa_modal" class="div_modal"></div>
        <div id="capa_para_edicion" class="div_contenido"><div>
        <input type="hidden" id="partido_seleccionado" value="0"  />
        <input type="hidden" id="seccion_seleccionada" value="0"  />
        
        <div class="margin"  id="botones_control" >
            <button type="button" class="btn btn-primary" onclick="mostrarseccion(1);" >Informacion</button>
            <button type="button" class="btn btn-primary" onclick="mostrarseccion(2);" >Educación</button>
        </div>
    
        <div  id="contenido_capa_edicion" ></div>
        
    </section>

resources/views/layouts/partials/notifications.blade.php
            <li class="dropdown notifications-menu">           
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-bell-o"></i>
                <span class="label label-warning">10</span>
                </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>               
                <ul class="menu">
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>                 
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>  

resources/views/layouts/partials/search.blade.php
    <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </form>

resources/views/layouts/partials/tasks.blade.php
            <li class="dropdown tasks-menu">            
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-flag-o"></i>
                <span class="label label-danger">0</span>
                </a>
            <ul class="dropdown-menu">
              <li class="header">Tienes 2 Tareas</li>
              <li>              
                <ul class="menu">
                  <li><a href="#"><h3>Ver putas<small class="pull-right">20%</small></h3></a></li>
                  <li><a href="#"><h3>Analizar<small class="pull-right">20%</small></h3></a></li>
                </ul>
              </li>
              <li class="footer">
                <a href="#">Ver todas las tareas</a>
              </li>
            </ul>
          </li>

resources/views/layouts/partials/top.blade.php
<header class="main-header">
    @include('layouts.partials.logo')

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">           
                @include('layouts.partials.userinfo')
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/partials/userinfo.blade.php
        <li class="dropdown user user-menu"> 
        @auth            
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">             
              <img src="{{ auth()->user()->img }}" class="user-image" alt="User Image"> 
                         
              <span class="hidden-xs"> {{ auth()->user()->nombre }} </span>
            </a>
            <ul class="dropdown-menu">            
              <li class="user-header">
                <img src="{{ auth()->user()->img }}" class="img-circle" alt="User Image">
                <p> Player {{ auth()->user()->id }} - {{ auth()->user()->nombre }} {{ auth()->user()->apellido }} </p>
              </li>             
              <li class="user-body">
                <div class="row">
                  
                </div>                
              </li>             
              <li class="user-footer">
                <div class="pull-left">
                  <a href="/usuarios/{{ auth()->id() }}/edit" class="btn btn-default btn-flat">Perfil</a>
                </div>
                <div class="pull-right">
                  <form method="POST" action="{{ route('logout') }}">
                    {{ csrf_field() }}
                    <button  class="btn btn-default btn-flat">Cerrar sesión</button>
                  </form>
                </div>
              </li>
            </ul>
          </li>
          @endauth