routes/web.php
<?php
// Route::get('roles', function(){
//     return \App\Role::with('user')->get();
// });

Route::get('/', function () { return view('welcome'); });
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/privacity', 'HomeController@privacity');
Route::get('/terms', 'HomeController@terminos');
Route::get('activate/{token}', 'ActivationTokenController@activate')->name('activation');

Auth::routes();

Route::resource('lista_partidos_oficiales', 'MatchController');
Route::resource('usuarios', 'UsersController');

Route::get('config14605145pro', 'QuinielaController@configApp')->name('configApp');
Route::get('config1968pro', 'QuinielaController@configQuinielas')->name('configQuinielas');
Route::get('cerrarpartido/{grupo}/{code}/{active}', 'QuinielaController@CerrarPartido');

Route::get('isadmintrue', 'ListaUsuariosController@isadminRole');

Route::get('ActualizarPuntosPartido/{code}', 'PointController@ActualizarPuntosPartido');

Route::get('tabla2', 'PointController@tabla2');

Route::get('configtablaPosiciones/{desde?}/{hasta?}', 'PositionController@basePosition');
Route::get('ActualizarPuntosPartido/{code}', 'PointController@procesarPartidoyCargarPuntos');
Route::get('tabla', 'PositionController@index');




Route::resource('quiniela', 'QuinielaController');
Route::resource('grupoA', 'GrupoAController');
Route::resource('grupoB', 'GrupoBController');
Route::resource('grupoC', 'GrupoCController');
Route::resource('grupoD', 'GrupoDController');
Route::resource('grupoE', 'GrupoEController');
Route::resource('grupoF', 'GrupoFController');
Route::resource('grupoG', 'GrupoGController');
Route::resource('grupoH', 'GrupoHController');

Route::get('resumen/{usuario?}', 'QuinielaController@index');


Route::get('lista', 'ListaUsuariosController@index');
Route::get('favoritas', 'ListaUsuariosController@favoritas');

app/GrupoE.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GrupoE extends Model
{
    protected $table = "grupo_e";
    protected $fillable = [
        'code', 'grupoFase', 'equipo_A', 'equipo_B', 'goles_A', 'goles_B', 'minGolesA', 'minGolesB', 'hourGame', 'activeGame'
    ];
    
    protected $dates = ['hourGame'];
    // protected $dateFormat = 'Y-m-d H:i:s';

    public function bandera($cadena)
    {
        $original =   'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûýýþÿŔŕ';
        $modificada = 'aaaaaaaceeeeiiiidnoooooouuuuybsaaaaaaaceeeeiiiidnoooooouuuyybyRr';
        $cadena = utf8_decode($cadena);
        $cadena = strtr($cadena, utf8_decode($original), $modificada);
        $cadena = strtolower($cadena);
        $cadena = utf8_encode($cadena);
        return substr($cadena, 0,3);
    }  
    
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Quiniela.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Quiniela extends Model
{
    protected $table = "quinielas";
    protected $fillable = [
        'code', 'grupoFase', 'equipo_A', 'equipo_B', 'goles_A', 'goles_B', 'minGolesA', 'minGolesB', 'hourGame', 'activeGame'
    ];
    
    protected $dates = ['hourGame'];
    // protected $dateFormat = 'Y-m-d H:i:s';

    public function bandera($cadena)
    {
        $original =   'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûýýþÿŔŕ';
        $modificada = 'aaaaaaaceeeeiiiidnoooooouuuuybsaaaaaaaceeeeiiiidnoooooouuuyybyRr';
        $cadena = utf8_decode($cadena);
        $cadena = strtr($cadena, utf8_decode($original), $modificada);
        $cadena = strtolower($cadena);
        $cadena = utf8_encode($cadena);
        return substr($cadena, 0,3);
    }

    public static function chooseGroup($grupo)
    {
        switch ($grupo) {
            case "grupoa":
                    $grupo = "Grupo A";
                break;
            case "grupob":
                $grupo = "Grupo B";
            break;
            case "grupoc":
                $grupo = "Grupo C";
            break;
            case "grupod":
                $grupo = "Grupo D";
            break;
            case "grupoe":
                $grupo = "Grupo E";
            break;
            case "grupof":
                $grupo = "Grupo F";
            break;
            case "grupog":
                $grupo = "Grupo G";
            break;
            case "grupoh":
                    $grupo = "Grupo H";
                break;
            default: '';          
        }  
        return $grupo;
    }

    public  function comprobarTabla($user)
    {      
        $user = \Auth::user()->id; 
        $partidos = GrupoA::where('user_id','=',$user)->get();               
        if(count($partidos)> 0){
            return redirect('/quiniela')->with('info', 'Ya tienes la quiniela lista para llenar');
        }
        
    }

        
}

app/Http/Controllers/GrupoEController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\GrupoE;
use App\Http\Requests\FillQuinielaRequest;
use Redirect;

class GrupoEController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['privacity', 'terms']]);
        
    }
    
    public function index()
    {
        $user = \Auth::user()->id;         
        $partidos = GrupoE::where('user_id','=',$user)->get();        
        return view('quiniela.grupo_e.index', compact('partidos'));
    }

    public function create()
    {       
    }

    public function store()
    {       
    }

    public function edit($id)
    {                                  
        $user = \Auth::user()->id;         
        $matches = GrupoE::where('user_id','=',$user)->get();
        $partido = GrupoE::findOrFail($id);          
        return view('quiniela.grupo_e.edit', compact('partido','matches'));
    }


    public function update(FillQuinielaRequest $request,  $id)
    {
        $partido = GrupoE::find($id);
       
        if(!$partido->activeGame == 1){
            $data = $request->all();
            $user_id = $data["user_id"];
            $partido->goles_A = $data["goles_A"];
            $partido->goles_B = $data["goles_B"];
            $partido->minGolesA = $data["minGolesA"];
            $partido->minGolesA = $data["minGolesA"];
            $partido->minGolesB = $data["minGolesB"];        

            $resul = $partido->save();
                if ($resul) {
                    return back()->with('info', 'Usuario Actualizado');
                } else {
                    return view("mensajes.rechazado")->with("msj", "hubo un error vuelva a intentarlo");
                }
        } else {
            return back()->with('info-err', 'Partido está cerrado, No se puede actualizar');
        }
    }

    public function show()
    {       
    }
}

app/Http/Controllers/QuinielaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Quiniela;
use App\Seleccion;
use App\Http\Requests\FillQuinielaRequest;
use App\GrupoA;
use App\GrupoB;
use App\GrupoC;
use App\GrupoD;
use App\GrupoE;
use App\GrupoF;
use App\GrupoG;
use App\GrupoH;
use App\User;
use App\Role;
use Redirect;
use Carbon\Carbon;
use DB;
use App\Http\Middleware\CheckRoles;
Use Auth;

class QuinielaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth',['except'=>['configQuinielas', 'index', 'comprobarTabla']]);
        $this->middleware('roles:admin',['except'=>['configQuinielas', 'index']]);
    }     

     public function index($id=null)

     {         
        
        if($id == null) { $id = \Auth::user()->id; } 
        $partidosA = GrupoA::where('user_id','=',$id)->get();         
        $partidosB = GrupoB::where('user_id','=',$id)->get();         
        $partidosC = GrupoC::where('user_id','=',$id)->get();         
        $partidosD = GrupoD::where('user_id','=',$id)->get();         
        $partidosE = GrupoE::where('user_id','=',$id)->get();         
        $partidosF = GrupoF::where('user_id','=',$id)->get();         
        $partidosG = GrupoG::where('user_id','=',$id)->get();         
        $partidosH = GrupoH::where('user_id','=',$id)->get(); 
        
        return view('quiniela.index', compact('partidosA','partidosB','partidosC','partidosD','partidosE','partidosF','partidosG','partidosH'));

     }   


    public function show($id)
    {       
    } 

    public function comprobarTabla($user)
    {      
        $user = \Auth::user()->id; 
        $partidos = GrupoA::where('user_id','=',$user)->get();               
        if(count($partidos)> 0){
            return redirect('/quiniela')->with('info', 'Ya tienes la quiniela lista para llenar');
        }        
    }
    
    public function configApp()
    {
        // $this->crearParDeUsers();
        $this->crearTablaSelecciones();
        $this->crearParDeRoles();
        return redirect('/');
    }

    public function crearTablaSelecciones()
    {
        $code =[
            'A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4', 'C1', 'C2', 'C3', 'C4', 'D1', 'D2', 'D3', 'D4', 'E1', 'E2', 'E3', 'E4', 'F1', 'F2', 'F3', 'F4', 'G1', 'G2', 'G3', 'G4', 'H1', 'H2', 'H3', 'H4'            
        ]; 
        $pais =[
            'Rusia', 'Arabia Saudita', 'Egipto', 'Uruguay', 'Portugal', 'España', 'Marruecos', 'Irán', 'Francia', 'Australia', 'Perú', 'Dinamarca', 'Argentina', 'Islandia', 'Croacia', 'Nigeria', 'Brasil', 'Suiza', 'Costa Rica', 'Serbia', 'Alemania', 'México', 'Suecia', 'Corea', 'Bélgica', 'Panamá', 'Tunez', 'Inglaterra', 'Polonia', 'Senegal', 'Colombia', 'Japón'         
        ];         
        $bandera =[
            'Rus', 'Ara', 'Egi', 'Uru', 'Por', 'Esp', 'Mar', 'Ira', 'Fra', 'Aus', 'Per', 'Din', 'Arg', 'Isl', 'Cro', 'Nig', 'Bra', 'Sui', 'Cost', 'Ser', 'Ale', 'Mex', 'Sue', 'Cor', 'Bel', 'Pan', 'Tun', 'Ing', 'Pol', 'Sen', 'Col', 'Jap'         
        ];         

        for ($i=0; $i < 32 ; $i++) { 
            $seleccion = new Seleccion;
            $seleccion->code =  $code[$i];
            $seleccion->pais = $pais[$i];           
            $seleccion->bandera = $bandera[$i];           
            $seleccion->save();
        }    
    }

    public function crearParDeUsers()
    {       
        $name = ['Admin', 'Wilmer']; 
        $lastname = ['Golpro', 'Castellanos']; 
        $cum = ['1968-12-23', '1980-10-19']; 
        $telf = ['123456789', '04147585086'];  
        $ced = ['123456789', '14605145'];  
        $mail = ['systemprogrampro@gmail.com', 'wilmerjaviercastellanos@gmail.com'];  
        $imagen = ['/img/player.jpg', '/img/player.jpg'];  
                   
        for ($i=0; $i < 2 ; $i++) { 
            $usuario = new User;
            $usuario->nombre = $name[$i]; 
            $usuario->apellido = $lastname[$i]; 
            $usuario->birthday = $cum[$i]; 
            $usuario->telefono = $telf[$i];  
            $usuario->cedula = $ced[$i];  
            $usuario->email = $mail[$i];  
            $usuario->img = $imagen[$i];          
            $usuario->password = bcrypt('LIsumubi24');           
            $usuario->save();
        }
    }

    public function crearParDeRoles()
    {       
        $nombre = ['admin', 'player', 'vip']; 
        $mostrar = ['Admin', 'Player','Vip']; 
        $desc = ['Administrador', 'Jugador', 'Jugador Vip'];        

        for ($i=0; $i < 3 ; $i++) { 
            $role = new Role;
            $role->name = $nombre[$i]; 
            $role->display_name = $mostrar[$i]; 
            $role->description = $desc[$i];                     
            $role->save();
        }
    } 

    public function configQuinielas()
    {
        $error = null;
        $user = \Auth::user()->id;
        if(!$this->comprobarTabla($user) )
        {
                DB::beginTransaction();
                try {
                        $this->createGrupoA();
                        $this->createGrupoB();
                        $this->createGrupoC();
                        $this->createGrupoD();
                        $this->createGrupoE();
                        $this->createGrupoF();
                        $this->createGrupoG();
                        $this->createGrupoH();
                    DB::commit();
                    $success = true;      
                    return redirect('/grupoA')->with('info', 'Ya tienes la quiniela lista para llenar');
                    } catch (\Exception $e) {
                        $success = false;
                        $error = $e->getMessage();
                        DB::rollback();
                    } 
                }          
        else {
            return redirect('/quiniela')->with('info', 'Ya tienes la quiniela lista para llenar');
        }       
    }
    
    public function createGrupoA()
    {     
        $equipo = Seleccion::all();
        $A1 = $equipo[0]['pais']; $cA1 = $equipo[0]['code'];
        $A2 = $equipo[1]['pais']; $cA2 = $equipo[1]['code'];
        $A3 = $equipo[2]['pais']; $cA3 = $equipo[2]['code'];
        $A4 = $equipo[3]['pais']; $cA4 = $equipo[3]['code'];

        $bA1 = $equipo[0]['bandera'];
        $bA2 = $equipo[1]['bandera'];
        $bA3 = $equipo[2]['bandera'];
        $bA4 = $equipo[3]['bandera'];

        $code = [$cA1.$cA2,$cA3.$cA4, $cA1.$cA3, $cA4.$cA2,$cA2.$cA3, $cA4.$cA1];       
        $equipo_A = [$A1, $A3, $A1, $A4, $A2, $A4];
        $flat_A =   [$bA1, $bA3, $bA1, $bA4, $bA2, $bA4];
        $equipo_B = [$A2, $A4, $A3, $A2, $A3, $A1];
        $flat_B = [$bA2, $bA4, $bA3, $bA2, $bA3, $bA1];

        $grupoAActive = [
            '1',   //  A1A2
            '1',   //  A3A4
            '0',   //  A1A3
            '0',   //  A4A2
            '0',   //  A2A3
            '0',   //  A4A1
        ];
        
        $hourGame =['2018-06-14 11:00:00', '2018-06-15 08:00:00', '2018-06-19 14:00:00', '2018-06-20 11:00:00', '2018-06-25 10:00:00', '2018-06-25 10:00:00'];       

        for ($i=0; $i < 6 ; $i++) { 
            $cuenta = new GrupoA;
            $cuenta->code =  $code[$i];
            $cuenta->grupoFase = 'Grupo A';
            $cuenta->equipo_A = $equipo_A[$i];
            $cuenta->flat_A = $flat_A[$i];
            $cuenta->equipo_B = $equipo_B[$i];            
            $cuenta->flat_B = $flat_B[$i];            
            $cuenta->activeGame = $grupoAActive[$i];
            $cuenta->hourGame = $hourGame[$i];
            $cuenta->visible = 1;
            $cuenta->user_id =  \Auth::user()->id; 
            $cuenta->save();
        }       
    }
    
    public function createGrupoB()
    {
        $equipo = Seleccion::all();
        $A1 = $equipo[4]['pais']; $cA1 = $equipo[4]['code'];
        $A2 = $equipo[5]['pais']; $cA2 = $equipo[5]['code'];
        $A3 = $equipo[6]['pais']; $cA3 = $equipo[6]['code'];
        $A4 = $equipo[7]['pais']; $cA4 = $equipo[7]['code'];

        $bA1 = $equipo[4]['bandera'];
        $bA2 = $equipo[5]['bandera'];
        $bA3 = $equipo[6]['bandera'];
        $bA4 = $equipo[7]['bandera'];

        $code = [$cA1.$cA2,$cA3.$cA4, $cA1.$cA3, $cA4.$cA2,$cA2.$cA3, $cA4.$cA1];       
        $equipo_A = [$A1, $A3, $A1, $A4, $A2, $A4];
        $flat_A = [$bA1, $bA3, $bA1, $bA4, $bA2, $bA4];
        $equipo_B = [$A2, $A4, $A3, $A2, $A3, $A1]; 
        $flat_B = [$bA2, $bA4, $bA3, $bA2, $bA3, $bA1];  

        $grupoBActive = [
            '1',   //  B1B2
            '1',   //  B3B4
            '0',   //  B1B3
            '0',   //  B4B2
            '0',   //  B2B3
            '0'   //  B4B1
        ];
        
        $hourGame =['2018-06-15 14:00:00', '2018-06-15 11:00:00', '2018-06-20 08:00:00', '2018-06-20 11:00:00', '2018-06-20 14:00:00',  '2018-06-25 14:00:00'];  

        for ($i=0; $i < 6 ; $i++) { 
            $cuenta = new GrupoB;
            $cuenta->code =  $code[$i];
            $cuenta->grupoFase = 'Grupo B';
            $cuenta->equipo_A = $equipo_A[$i];
            $cuenta->flat_A = $flat_A[$i];
            $cuenta->equipo_B = $equipo_B[$i];            
            $cuenta->flat_B = $flat_B[$i];            
            $cuenta->activeGame = $grupoBActive[$i];
            $cuenta->hourGame = $hourGame[$i];
            $cuenta->visible = 1;
            $cuenta->user_id =  \Auth::user()->id; 
            $cuenta->save();
        }        
    }

    public function createGrupoC()
    {
        $equipo = Seleccion::all();
        $A1 = $equipo[8]['pais']; $cA1 = $equipo[8]['code'];
        $A2 = $equipo[9]['pais']; $cA2 = $equipo[9]['code'];
        $A3 = $equipo[10]['pais']; $cA3 = $equipo[10]['code'];
        $A4 = $equipo[11]['pais']; $cA4 = $equipo[11]['code'];

        $bA1 = $equipo[8]['bandera'];
        $bA2 = $equipo[9]['bandera'];

resources/views/quiniela/grupo_e/edit.blade.php
@extends('layouts.master')
@section('content')<h1>Fase de Grupos  </h1>
   @if( session()->has('info') )
    <div class="alert alert-success">{{ session('info') }}</div> 
    @endif

    @if ( session()->has('info-err') )
    <div class="alert alert-danger">{{ session('info-err') }}</div>
    @endif

    @if(count($errors)> 0)
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <ul>
            @foreach($errors->all() as $error)
            <li>{!!$error!!}</li>
            @endforeach
        </ul>
    </div>
    @endif

    @foreach($matches as $match)
        <a href="/grupoE/{{$match->id}}/edit" class="btn btn-info btn-flat">ir a {{$match->equipo_A}} - {{$match->equipo_B}}</a>       
    @endforeach

    <div class="row">
       
        <div class="col-sm-12">
            <div class="box box-info ">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ $partido->grupoFase }} </h3> | <small> {{ $partido->hourGame }} Horas </small>
                </div>
                 <div id="Infopartido{{ $partido->code }}">
            </div>
                
                <form method="POST" action="{{route('grupoE.update', $partido->id )}}" id="{{ $partido->id }}" class="form-horizontal form_entrada  " >    
                    {!!   method_field('PUT') !!}
                    {!! csrf_field() !!} 
                    <div class="box-body">
                      <input type="hidden" class="form-control" name="user_id"  value=" {{auth()->user()->id  }} " > 
                      <div class="form-group">                       
                        <input type="hidden" class="form-control" name="code"  value=" {{ $partido->code }} ">                        
                      </div>
                      <div class="form-group">                        
                        <input type="hidden" class="form-control" name="grupoFase"  value=" {{ $partido->grupoFase }} ">                 
                      </div>
                        
                      <div class="form-group">
                          <label for="inputEmail3" class="col-sm-4 control-label">{{ $partido->equipo_A }}
                                <img src="/img/{{ $partido->flat_A }}.png">
                            </label>
                          <input type="hidden" class="form-control" name="equipo_A"  value=" {{ $partido->equipo_A }} "> 
                          <div class="col-sm-8">
                              <small>Cuántos goles hace</small>
                              <input type="text" class="form-control" name="goles_A"  value=" {{ $partido->goles_A }} " autocomplete="off"> 
                              {!! $errors->first('goles_A', '<span class=error>:message</span>') !!}
                              <small>Introduce los minutos en los que se podría dar cada gol, sepáralos por coma(,) si es cero deja en blanco</small>
                              <input type="text" class="form-control" name="minGolesA"   placeholder="ejemplo 5,27,90"  value=" {{ $partido->minGolesA }}" autocomplete="off">                                           
                          </div>
                      </div>                        
                    <hr>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-4 control-label">{{ $partido->equipo_B }} 
                                    <img src="/img/{{ $partido->flat_B }}.png">
                            </label>
                            <input type="hidden" class="form-control" name="equipo_B"  value=" {{ $partido->equipo_B }} ">
                            <div class="col-sm-8">
                                <small>Cuántos goles hace</small>
                                <input type="text" class="form-control" name="goles_B"  value=" {{ $partido->goles_B }} " autocomplete="off"> 
                                {!! $errors->first('goles_B', '<span class=error>:message</span>') !!}
                                <small>Introduce los minutos en los que se podría dar cada gol, sepáralos por coma(,) si es cero deja en blanco</small>
                                <input type="text" class="form-control" name="minGolesB"   value= " {{ $partido->minGolesB }}" placeholder="ejemplo 5,27,90"  autocomplete="off"> 
                                                      
                            </div>
                        </div>             

                    </div>
                    
                    <div class="box-footer">
                                      
                        <button type="submit" class="btn btn-info pull-right">Guardar</button>
                    </div>
                
                </form>
                 
                  
            </div>
        </div>
        {{-- <div class="col-sm-6">
             <div class="box box-info ">
                <div class="box-header with-border">
                    <h3 class="box-title"> Partidos del grupo A</h3>
                </div>
            
            <div class="box-body">
                <div class="btn-group">
                    <a type="button" class="btn btn-info">1</a>
                    <a type="button" class="btn btn-info">2</a>
                    <a type="button" class="btn btn-info">3</a>
                    <a type="button" class="btn btn-info">4</a>
                    <a type="button" class="btn btn-info">5</a>
                    <a type="button" class="btn btn-info">6</a>
                </div>
            </div>
            <div class="box-footer">
            </div>
            </div>
       
        </div> --}}
@stop
 

resources/views/quiniela/grupo_e/index.blade.php
@extends('layouts.master')
@section('content')
<h1>Fase de Grupos  </h1>
   

    <div class="row">
    @foreach($partidos as $partido)
        <div class="col-sm-6 col-lg-2">
            <div class="box box-info ">
                <div class="box-header with-border">
                    <h3 class="box-title">
                            @if($partido->activeGame == 1)
                            <div class="text-danger">  Cerrado </div>
                            @endif
                        {{ $partido->grupoFase }} </h3>  <small> {{ $partido->hourGame->format('d M Y | H:i:s ') }}  </small>
                </div>
              

                <div id="Infopartido{{ $partido->code }}"></div>
                
                <form method="POST" action="grupoE/edit/$partido->id" id="{{ $partido->id }}" class="form-horizontal form_entrada  " >         <div class="box-body">
                      <input type="hidden" class="form-control" name="user_id"  value=" {{auth()->user()->id  }} " > 
                      <div class="form-group">                       
                        <input type="hidden" class="form-control" name="code"  value=" {{ $partido->code }} ">                        
                      </div>
                      <div class="form-group">                        
                        <input type="hidden" class="form-control" name="grupoFase"  value=" {{ $partido->grupoFase }} ">                 
                      </div>
                        
                      <div class="form-group">
                          <label for="inputEmail3" class="col-sm-4 control-label">{{ $partido->equipo_A }}
                                <img src="/img/{{ $partido->flat_A }}.png">
                            </label>
                          <input type="hidden" class="form-control" name="equipo_A"  value=" {{ $partido->equipo_A }} "> 
                          <div class="col-sm-8">
                              
                             <h2> {{ $partido->goles_A }}</h2>
                         
                           
                            <small> {{$partido->minGolesA }}     </small>                                   
                          </div>
                      </div>                        
                    <hr>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-4 control-label">{{ $partido->equipo_B }} 
                                    <img src="/img/{{ $partido->flat_B }}.png">
                            </label>
                            <input type="hidden" class="form-control" name="equipo_B"  value=" {{ $partido->equipo_B }} ">
                            <div class="col-sm-8">
                               
                              <h2> {{ $partido->goles_B }} </h2>
                                
                               
                             <small> {{ $partido->minGolesB }} </small>
                                                      
                            </div>
                        </div>             

                    </div>
                    
                    <div class="box-footer">
                         
                         <a class="btn  btn-skin-green btn-xs pull-right" href="/grupoE/{{$partido->id}}/edit" >
                                <i class="fa fa-fw fa-eye"></i>Ver
                        </a>         
                        
                    </div>
                
                </form>
                 
                  
            </div>
        </div>
 
        @endforeach
    </div>

 @stop